### PR TITLE
Project3 el me

### PR DESCRIPTION
**Pull request by elvinhajizada**
Pull request from our group

### CODE REVIEW

**Review by janfb — CHANGES_REQUESTED** [review]
Hey! this PR contains changes to files outside of your `your-code` folder and cannot be merged (see `Files changed` in the PR above). I think you can undo most of these changes by discarding the last commit `updating from master` (797e1c4). 

In your second commit you also changed the exercise file in the `exercise` folder. please reset this file to original state. you can reset a single file using these instructions: https://fettblog.eu/snippets/git/reverting-a-single-file/

let me know if you have questions.

**Comment by elvinhajizada** [comment]
i tried to fix errors, now there should be no conflicts. Can you check again please

**Comment by janfb** [comment]
Thanks for the update. but unfortunately this is not fixed yet. You can check whether it is fixed by looking at `Files Changed` above: https://github.com/cne-tum/msne-lsmlsda-2019/pull/19/files 

There should not be any files outside of `your-code` that changed.

**Comment by elvinhajizada** [comment]
But I basically copied the outside of 'your code' folder from master branch. How can there be changed files in this case? I saw them them, but I don't understand. It already took me a lot of time

**Comment by janfb** [comment]
I dont know, I just see the changes. I would just reset all the files outside of your-code to the earliest commit of your new branch, that should do it (see the link I send you for how to do that).

Otherwise I can offer to help you tomorrow before the lecture, e.g., at 9:30?

Best,
Jan


On 28. May 2019, at 18:37, Elvin Hajizada <notifications@github.com<mailto:notifications@github.com>> wrote:


But I basically copied the outside of 'your code' folder from master branch. How can there be changed files in this case? I saw them them, but I don't understand. It already took me a lot of time

**Comment by elvinhajizada** [comment]
I think I solved the problem this time, now changed files are only from 'your_code' folder. 
But I am still confused, so help at 9:30 would be helpful

Best 
Elvin

**Comment by janfb** [comment]
Looks good! great that you fixed it. 

Regarding tomorrow, I would prefer to meet after the lecture, i.e., at 11:20?

**Review by janfb — APPROVED** [review]

**Comment by elvinhajizada** [comment]
Thanks for help and 11:20 is also suitable for me. Will you be in classroom or should I come somewhere inside ICS?

Best

**Comment by janfb** [comment]
Sure, I’ll meet you in the class room.

On 28. May 2019, at 19:59, Elvin Hajizada <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for help and 11:20 is also suitable for me. Will you be in classroom or should I come somewhere inside ICS?

Best

**Comment by elvinhajizada** [comment]
Okay, see you tomorrow then,

Best

**Pull request merged**
